### ISSUE TITLE
Allow symlinks when looking up/through fontpath

### ISSUE THREAD

**Issue by mmlb** [tomszilagyi/zutty#10]
Hey @tomszilagyi, I'm looking forward to getting this running on NixOS so I can give it a spin.

On NixOS the canonical path to the fonts is `/run/current-system/sw/share/X11/fonts` which is a symbolic link. zutty does not traverse into the the destination because of the `FTW_PHYS` in ` int flags = FTW_DEPTH | FTW_PHYS;` in  https://github.com/tomszilagyi/zutty/blob/master/src/fontpack.cc#L187. I'm not exactly sure if that's really necessary. I can dereference the symlink and provide the full/concrete path of course, but I'd like to just use the symlink if possible.

Beside the issue with `fontpath` itself, all of the non-Xorg provided fonts that reside in fontpath are themselves symlinks and zutty skips over them. Fixing that means dropping https://github.com/tomszilagyi/zutty/blob/master/src/fontpack.cc#L83.

Would both of these be OK? Happy to setup a PR.

**Comment by tomszilagyi** [comment]
Would the removal of `FTW_PHYS` from `flags` make `nftw ()` to follow symlinks, so that a symlink will transparently result in looking at the pointed-to file, so that the check at L83 remains valid? At least that is how I would imagine this to work.

**Comment by mmlb** [comment]
Hi @tomszilagyi thanks for fixing this!
