### ISSUE TITLE
Sixel support

### ISSUE THREAD

**Issue by HalosGhost** [tomszilagyi/zutty#12]
I *love* Zutty's focus on standards-compliance. It is, by far, one of the things I wish more TEs handled well. One of the standards I would love to see more wide support for is Sixel graphics. These were originally offered by DEC, though, as far as I know, they never made it into any specific VT standard.

The modern, maintained reference library is [on github](https://github.com/saitoha/libsixel), but as I understand it, sixel is pretty easy to implement from-scratch.

I'm not sure if this would ever be considered in-scope for Zutty, but it's definitely something I'd love to see more support for!

**Comment by tomszilagyi** [comment]
This is out of scope and technically challenging given how zutty works under the hood: https://tomscii.sig7.se/2020/11/How-Zutty-works
