### ISSUE TITLE
Support decoupling bold attr from bright colors

### ISSUE THREAD

**Issue by ogdenjosh** [tomszilagyi/zutty#16]
As far as I know, vt100 is where we get bold text as displaying in bright colors, however in xterm (if I remember right), this was configurable. Currently zutty will try to force bold text to use colors 8-15 rather than 0-7; could we possibly get a non-default option to disable this?

**Comment by tomszilagyi** [comment]
VT100 did not have any color, and neither did the VT220. I believe xterm adopted color support based on the relevant ANSI (ECMA-48) standard, and the convention to shift the color of cells marked with the bold attribute to the brighter variant (upper 8 colors) originates with the IBM PC. In xterm, the option that enables this (enabled by default) is called `boldColors`.

**Comment by tomszilagyi** [comment]
Apparently, GitHub's logic does not understand that this issue should now be closed, so closing it manually (implemented in dc6e37d).
