### ISSUE TITLE
Zutty on FreeBSD

### ISSUE THREAD

**Issue by reebsd** [tomszilagyi/zutty#18]
Right now, Zutty can be made to compile and run on FreeBSD.  Here are the steps I use to do so:
https://github.com/tomszilagyi/zutty/pull/17

However, things aren't 100% right yet.  Notably, job control isn't working in multiple shells, as discussed in this older pull request:
https://github.com/tomszilagyi/zutty/pull/8

I'll try out Zutty's tests today and post the results by replying to this issue.

(I'll also warn that I don't use GitHub often)

**Comment by tomszilagyi** [comment]
Regarding the job control:
There is a bit of conditional compilation for BSD in pty.cc near line 123 for acquiring a controlling terminal:
https://github.com/tomszilagyi/zutty/blob/f3fcf8e92b22e58b30947cf2585e361106dbcf9d/src/pty.cc#L123
I never tested this myself. Maybe the #ifdef does not work? Can you check if it works if you change `#if defined(BSD)` to `#if defined(_FreeBSD_)`? Or if you just remove the surrounding `#if` and `#endif` lines?

**Comment by tomszilagyi** [comment]
> (I'll also warn that I don't use GitHub often)

Feel free to email me directly (my address in commits), if that suits your workflow better.

**Comment by tomszilagyi** [comment]
I think I found the culprit, the symbol `BSD` simply never got defined (never tested it, never worked). It would be great if you could confirm that removing the #if ... #endif (unconditionally compiling the code between them) solves the "no job control" problem.

**Comment by reebsd** [comment]
> Regarding the job control:
> There is a bit of conditional compilation for BSD in pty.cc near line 123 for acquiring a controlling terminal:
> 
> https://github.com/tomszilagyi/zutty/blob/f3fcf8e92b22e58b30947cf2585e361106dbcf9d/src/pty.cc#L123
> 
> I never tested this myself. Maybe the #ifdef does not work? Can you check if it works if you change `#if defined(BSD)` to `#if defined(_FreeBSD_)`? Or if you just remove the surrounding `#if` and `#endif` lines?

> I think I found the culprit, the symbol `BSD` simply never got defined (never tested it, never worked). It would be great if you could confirm that removing the #if ... #endif (unconditionally compiling the code between them) solves the "no job control" problem.

You're right!  When I eliminate the `#if` and `#endif` I get working job control.  I'll have further info in just a couple minutes.

> > (I'll also warn that I don't use GitHub often)
> 
> Feel free to email me directly (my address in commits), if that suits your workflow better.

Thanks, I've just done so.

**Comment by reebsd** [comment]
So, there are two ways to fix this.
A: Add `#include <sys/param.h>` to `src/pty.cc` so the `BSD` symbol is defined.
B: Change `#if defined(BSD)` to `#if defined(__FreeBSD__)` (no inclusion of `sys/param.h` necessary, but this wouldn't work on NetBSD, OpenBSD, or DragonFlyBSD)

This is documented here:
https://docs.freebsd.org/en_US.ISO8859-1/books/porters-handbook/porting-versions.html

**Comment by reebsd** [comment]
After
https://github.com/tomszilagyi/zutty/commit/f867b72e95f29cfa5e02549d91a510a7eb5c0eac
Zutty builds and runs on FreeBSD as is, without any changes needed.  Thanks! :D
(using `-fontpath` is still required, however)

**Comment by tomszilagyi** [comment]
Excellent, thanks for confirming!

To get rid of `-fontpath`, you could configure it permanently in your `.Xresources` by adding this line:
```
Zutty.fontpath: /usr/local/share/fonts
```
(as per the usage guide: https://tomscii.sig7.se/zutty/doc/USAGE.html)
