### ISSUE TITLE
Consider using fontconfig lib for font discovery

### ISSUE THREAD

**Issue by 414owen** [tomszilagyi/zutty#28]
The assumption of `/usr/share/fonts` and similar paths doesn't hold on some systems, for example `nixos` and `guix` packages have their own root directories.

As a consequence, I have to find the path of a font in the `nix` store if I want to use it, which looks like this: `zutty -fontpath /nix/store/z3jdd0ydk50kwxbsxqp4648ybsxfai8z-inconsolata-2019-07-14/share/fonts -font "Inconsolata"`

These systems do however have `fontconfig` support, which reads from `/etc/fonts/conf.d/`.

**Comment by mmlb** [comment]
I'd welcome fontconfig support in zutty, but you might be able to do the same thing I'm doing under NixOS, I'm setting fontpath to `/run/current-system/sw/share/X11/fonts`

**Comment by planet36** [comment]
Would fontconfig allow zutty to search for fonts in `$XDG_DATA_HOME/fonts`?

**Comment by tomszilagyi** [comment]
Thanks for the suggestion.
The problem is due to the idiosyncrasy of nix/guix -- hardly any other platform resembling unix is going to have this issue.
Even on nix/guix, there is an easy workaround as @mmlb was kind enough to share.
Plus, I see a downside in adding a dependency on fontconfig.
