### ISSUE TITLE
-border option offsets selections

### ISSUE THREAD

**Issue by mjklbhvg** [tomszilagyi/zutty#35]
Hi,

while using zutty I just noticed the following bug:

Executing zutty with
-border 50
(or setting 'Zutty.border: 50') in .Xresources) will cause every selection to be offset from the mouse cursor.

Subtracting 'opts.border' from the mouse coordinates in 'onMotionNotify' and 'onButtonPress' in main.cc fixes the issue.
I am not sure if it is a proper solution though, because I have never worked with X.

**Comment by tomszilagyi** [comment]
Many thanks for reporting this!
