### ISSUE TITLE
set x icon 

### ISSUE THREAD

**Issue by MathGeniusJodie** [tomszilagyi/zutty#36]
I see you have added icons, are you planning to make x aware of those icons so that window managers and panels can display them? I originally thought this was an issue with tint2 (the panel I use), but according to https://gitlab.com/o9000/tint2/-/issues/726 it's a problem with the individual applications

**Comment by tomszilagyi** [comment]
I don't really have a ready environment to test this (I use i3 tiling WM everywhere, which is an environment without icons), so my knowledge in this area is limited.

But I was hoping that the purpose of the Icon entry within the .desktop file (if installed in the right place, etc) would be that desktop environments / WMs can display the icon in the place and with the resolution that they want, without all applications having to do gymnastics on their own.

I do know about _NET_WM_ICON as exposed by the freedesktop.org specs, and I would really like to avoid that "solution". Why should the program need to dump its icon as an uncompressed rgba blob (or set of blobs, for various resolutions) into property values on the X server? Why not load the icons from file (any of the provided raster sizes, or rasterize the vector image to any desired resolution) within the desktop env that wants to display icons? It's a bit like if the application was tasked with providing raw bitmaps for its own window decorations. As an application, I do not want to have to care about how (if at all) the WM displays my icon. I do hope there is a mechanism that works like this (I believed the .desktop entry is it, but apparently not).

So... do you have a more specific (technical) description (standard/prior art) of what an application is supposed to do to "set x icon" that is *not* _NET_WM_ICON (that is to say, it works by somehow directing the attention of the desktop environment or X to the icon files for them to use) *and* works across all major desktops? If yes, I am happy to consider implementing it!

**Comment by MathGeniusJodie** [comment]
the desktop entries tend to work fine for launchers, _NET_WM_ICON is for window managers and task bars, afaik there isn't another way to do this (at least for some taskbars and window managers, I've only tested on one)

**Comment by paxet** [comment]
I'm using Zutty with a Void Linux setup using Gnome as DE.
When launching zutty through the desktop file (included in this repo) I can see the icon in the taskbar.
