### ISSUE TITLE
404 on HACKING.org

### ISSUE THREAD

**Issue by pveentjer** [tomszilagyi/zutty#41]
On the following page:

https://github.com/tomszilagyi/zutty/blob/master/doc/HACKING.org

At the following text:

```
Test your changes thoroughly

At a minimum, run all regression tests via The CI test script before pull-requesting any change.
```
The link 'The CI test script' that links to https://github.com/tomszilagyi/zutty/blob/master/doc/The%20CI%20test%20script gives a 404.

**Comment by tomszilagyi** [comment]
I gave up on Github's org-mode renderer :)
Please look at the documentation hosted under https://tomscii.sig7.se/zutty/ which is the same document but exported via emacs's org-mode.

**Comment by pveentjer** [comment]
Ok. Thanks.
