### ISSUE TITLE
unhandled OSC: '112;' and '7;some_dir'

### ISSUE THREAD

**Issue by mirsemen** [tomszilagyi/zutty#43]
Zutty 0.9-1-gb8849be
OS: Gentoo (Calculate)
WM: i3-gaps-4.19.1

My zutty-related settings in .Xresources are:
```
Zutty.title:                   The Big Zutty
Zutty.altScroll:               true
Zutty.boldColors:              true
Zutty.font:                    Hack Regular Nerd Font Complete Mono
Zutty.fontsize:                24
Zutty.fg:                      #E3DBB2
Zutty.bg:                      #282828
Zutty.cr:                      #0f0
Zutty.modifyOtherKeys:         2
Zutty.altSendsEscape:          true
```
When I launch Zutty from another terminal - it prints a warning:
```
W [main.cc:1112] (Unimplemented) unhandled OSC: '7;file://mirgorodskiy/home/sem'
```
whenever you change to a new directory.

After starting NeoVim (nvim) in Zutty, the following lines are printed:
```
W [main.cc:1112] (Unimplemented) unhandled OSC: '112;'
E [vterm.icc: 91] Error: Unhandled input char 'q' (113) in state CSI_SPC. Escape sequence so far: '\e[1 q' (5 bytes)
```

In the editor, when you press NumLock, the cursor moves word by word, as if pressing the "W" key. The same thing happens when you switch the layout (I switch it by pressing the "CapsLock" key).

When launching the Vim editor:
```
W [vterm.icc:1399] (Unimplemented) Start blinking cursor
W [vterm.icc:1449] (Unimplemented) Stop blinking cursor
W [vterm.icc:1623] (Unimplemented) attribute: 29
W [vterm.icc:1623] (Unimplemented) attribute: 29
```
but the editor behaves correctly on NumLock.

**Comment by tomszilagyi** [comment]
`W [main.cc:1112] (Unimplemented) unhandled OSC: '7;file://mirgorodskiy/home/sem'`
I do not see any spec for this ([source](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands)) so I think it is rightly unimplemented (and ignored). What would you like to happen? What other terminal does that today?

`[main.cc:1112] (Unimplemented) unhandled OSC: '112;'`
Reset text cursor color. Harmless to ignore.

`[vterm.icc: 91] Error: Unhandled input char 'q' (113) in state CSI_SPC. Escape sequence so far: '\e[1 q' (5 bytes)`
This is listed as `CSI Ps SP q` a.k.a DECSCUSR in the above linked reference. Here, Ps=1, so this is an instruction for the cursor to be set to blinking block (default). This is not implemented, as clearly stated by the Zutty documentation. The cursor is still a block, but without the blinking.

Regarding your next two sentences, I am not familiar with how Vim behaves and I don't understand your reference to layout switching, so I am going to ignore that. Please come up with a more elaborate bug report focused on that, if you wish.

```
W [vterm.icc:1399] (Unimplemented) Start blinking cursor
W [vterm.icc:1449] (Unimplemented) Stop blinking cursor
```
This is normal, blinking is not implemented, as clearly documented.

```
W [vterm.icc:1623] (Unimplemented) attribute: 29
W [vterm.icc:1623] (Unimplemented) attribute: 29
```
Attribute 29 is "Not crossed-out". I hope you don't mind that this is not implemented.
