### ISSUE TITLE
Poor performance on Raspberry Pi 1

### ISSUE THREAD

**Issue by wryun** [tomszilagyi/zutty#46]
It was incredibly slow and pegged my CPU to 100%. I expect this is because there's some OpenGL ES 3 emulation going on - from brief googling, it only supports OpenGL ES 2 - but I'm not at all familiar with any of this. I wondered if anyone had some ideas on where to start digging (aside from, I dunno, running a profiler :) ).

**Comment by wryun** [comment]
Ok, this was just me not realising that raspbian uses the fbturbo driver by default rather than the vc4 kms driver. Once I enabled that, I got a nice message about not supporting GLSL 3.1 (only 1.0).

Out of curiosity, would it be possible to use GLSL 1.0, or are there critical features that require 3.1?

**Comment by tomszilagyi** [comment]
All your questions are answered by the README and the FAQ.
