### ISSUE TITLE
Another binary cat... received signal SIGABRT, Aborted.

### ISSUE THREAD

**Issue by mones** [tomszilagyi/zutty#48]
Hi Tom, first thanks for fixing #47 so fast, that one is not reproducible anymore :+1: 

But the bug is not completely fixed, seems other sequences can make Zutty crash. This is last HEAD, built with --debug.
This backtrace was made by 'cat /usr/bin/callgraph' (callgraph comes from golang-golang-x-tools 1:0.1.0+ds-1+b5 package in Debian testing). Last chars printed to console also included:

[...]
E [vterm.icc: 91] Error: Unhandled input char '�' (215) in state Escape. Escape sequence so far: '\e\xd7' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '�' (128) in state Escape. Escape sequence so far: '\e\x80' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '�' (229) in state Escape. Escape sequence so far: '\e\xe5' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '' (6) in state Escape. Escape sequence so far: '\e\x06' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '' (0) in state Escape. Escape sequence so far: '\e\x00' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '' (0) in state Escape. Escape sequence so far: '\e\x00' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '_' (95) in state Escape. Escape sequence so far: '\e_' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '' (0) in state Escape. Escape sequence so far: '\e\x00' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char 'f' (102) in state Escape. Escape sequence so far: '\ef' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char 'd' (100) in state Escape. Escape sequence so far: '\ed' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '�' (151) in state Escape. Escape sequence so far: '\e\x97' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '' (25) in state Escape. Escape sequence so far: '\e\x19' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char 'T' (84) in state Escape. Escape sequence so far: '\eT' (2 bytes)
E [vterm.icc: 91] Error: Unhandled input char '�' (136) in state Escape. Escape sequence so far: '\e\x88' (2 bytes)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Frame::getIdx (pY=23 pX=80) out of bounds, nCols=80, nRows=24

Thread 1 "zutty.dbg" received signal SIGABRT, Aborted.
0x00007ffff783ece1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt full
#0  0x00007ffff783ece1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff7828537 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007ffff7bc383e in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff7bce986 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff7bce9f1 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff7bcec75 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x000055555558ac19 in zutty::Frame::getIdx (
    this=this@entry=0x555555861818, pY=pY@entry=23, pX=pX@entry=80)
    at /usr/include/c++/10/ext/new_allocator.h:89
        oss = <incomplete type>
#7  0x0000555555586178 in zutty::Frame::getCell (pX=80, pY=23, 
    this=0x555555861818) at ../src/frame.icc:107
        idx = <optimized out>
        idx = <optimized out>
#8  zutty::Vterm::placeGraphicChar (this=0x5555558617c0)
    at ../src/vterm.icc:521
        c = <optimized out>
        c = <optimized out>
#9  operator() (__closure=<optimized out>) at ../src/vterm.cc:594
        this = <optimized out>
        this = <optimized out>
#10 std::__invoke_impl<void, zutty::Vterm::Vterm(uint16_t, uint16_t, uint16_t, uint16_t, int)::<lambda()>&> ( 
    __f=...) at /usr/include/c++/10/bits/invoke.h:60
No locals.
#11 std::__invoke_r<void, zutty::Vterm::Vterm(uint16_t, uint16_t, uint16_t, uint16_t, int)::<lambda()>&> ( 
    __fn=...) at /usr/include/c++/10/bits/invoke.h:153
No locals.
#12 std::_Function_handler<void(), zutty::Vterm::Vterm(uint16_t, uint16_t, uint16_t, uint16_t, int)::<lambda()> >::_M_invoke(const std::_Any_data &) (
    __functor=...) at /usr/include/c++/10/bits/std_function.h:291
No locals.
#13 0x000055555557fdbe in std::function<void ()>::operator()() const ( 
    this=this@entry=0x555555869c80)
    at /usr/include/c++/10/bits/std_function.h:622
No locals.
#14 0x000055555558a848 in zutty::Utf8Decoder::pushByte (
    this=this@entry=0x555555869c78, ch=ch@entry=133 '\205')
    at ../src/utf8.h:105
No locals.
#15 0x000055555558682b in zutty::Vterm::inputGraphicChar (ch=133 '\205', 
    this=0x5555558617c0) at ../src/vterm.icc:497
        cs = <optimized out>
#16 zutty::Vterm::processInput (this=this@entry=0x5555558617c0, 
    input=input@entry=0x555555861c1a "\354\001", 
    inputSize=inputSize@entry=4095) at ../src/vterm.cc:1038
        ch = <optimized out>
#17 0x000055555557a1c9 in zutty::Vterm::readPty (this=0x5555558617c0)
    at ../src/vterm.icc:382
        first = false
        n = 4095
#18 0x0000555555577025 in eventLoop (xic=@0x7fffffffdd78: 0x55555585e020, 
    ptyFd=ptyFd@entry=7) at /usr/include/c++/10/bits/unique_ptr.h:173
        x11Fd = <optimized out>
        pollset = {{fd = 7, events = 1, revents = 1}, {fd = 3, events = 1, 
            revents = 0}}
        holdPtyIn = false
#19 0x0000555555578d86 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/main.cc:1379
        eglSurface = 0x55555585c0a0
        eglCtx = 0x5555556f12d0
        eglDpy = 0x555555609450
        eglMajor = 1
        eglMinor = 5
        xic = 0x55555585e020
        xim = <optimized out>
        ximStyles = 0x5555556e8110
        ximStyle = <optimized out>
        imvalret = <optimized out>
        i = <optimized out>
        argv0 = "bash", '\000' <repeats 4091 times>
        progPath = "/bin/bash", '\000' <repeats 4086 times>
        defaultShArgv = {0x7fffffffcd70 "bash", 0x0}
        shArgv = <optimized out>
        winWidth = 724
        winHeight = 436
        ptyFd = 7
        destroyed = <optimized out>

**Comment by tomszilagyi** [comment]
Would you mind attaching the binary or sending it to me via email? (A corresponding md5 / sha1 / sha256 checksum would also be appreciated.) At the moment I don't have an instance of Debian testing around. Thanks!

**Comment by mones** [comment]
Sure, no problem, this is the URL of the exact package I have currently installed:

https://snapshot.debian.org/archive/debian/20210718T144801Z/pool/main/g/golang-golang-x-tools/golang-golang-x-tools_0.1.0%2Bds-1%2Bb5_amd64.deb

Don't need to install it, just open it and extract somewhere the "callgraph" file from the inner data.tar.xz. file (it's in a usr/bin path, but don't need to keep folder structure).

md5sum: bea2adc378582c481a82f0d809671331 /usr/bin/callgraph
sha1sum: 81b420f293e4940c296f5183e7d7d761d90f6bc2 /usr/bin/callgraph
sha256sum: 50bf1c5af6dd5a4b1e285290703089085ca16e46bba6069180dea062d0a160f8 /usr/bin/callgraph

**Comment by mones** [comment]
Thanks Tom! No binary under my /usr/bin makes it crash anymore ;-)
