### ISSUE TITLE
Double click to select a word

### ISSUE THREAD

**Issue by xyproto** [tomszilagyi/zutty#49]
There is only one thing that I'm missing from Zutty, and that's the ability to double-click a word to select it.

This is a feature request for that feature.

**Comment by tomszilagyi** [comment]
Excellent suggestion!

**Comment by xyproto** [comment]
Oh, and triple click to select the whole line is also very useful. :slightly_smiling_face:

**Comment by xyproto** [comment]
Nice, I just tested it and the double-click feature works great. :+1:
