### ISSUE TITLE
Configure fails to detect unsupported GLSL ES version

### ISSUE THREAD

**Issue by Earnestly** [tomszilagyi/zutty#5]
As a result I'm not able to use this emulator, which is a pity.  If a `configure` stage is to be used it might well check for the needed version and warn the user (an error seems unresonable if zutty is intended to run on a different machine to which it was built).

```
% ./waf configure
Setting top to                           : /home/earnest/zutty
Setting out to                           : /home/earnest/zutty/build
Zutty version                            : 0.6-8-gc792cf1
Debug build                              : no
Checking for 'g++' (C++ compiler)        : /usr/bin/g++
Checking for program 'pkg-config'        : /usr/bin/pkg-config
Checking for 'freetype2'                 : yes
Checking for 'xmu'                       : yes
Checking for header EGL/egl.h            : yes
Checking for header GLES3/gl31.h         : yes
'configure' finished successfully (5.259s)

% ./waf build
Waf: Entering directory `/home/earnest/zutty/build'
[ 1/12] Compiling src/options.cc
[ 2/12] Compiling src/fontpack.cc
[ 3/12] Compiling src/charvdev.cc
[ 4/12] Compiling src/selmgr.cc
[ 5/12] Compiling src/frame.cc
[ 6/12] Compiling src/vterm.cc
[ 7/12] Compiling src/gl.cc
[ 8/12] Compiling src/renderer.cc
[ 9/12] Compiling src/pty.cc
[10/12] Compiling src/font.cc
[11/12] Compiling src/main.cc
[12/12] Linking build/src/zutty
Waf: Leaving directory `/home/earnest/zutty/build'
'build' finished successfully (15.732s)

% ./build/src/zutty
E [charvdev.cc:181] Error: Compiling fragment shader:
0:1(10): error: GLSL ES 3.10 is not supported. Supported versions are: 1.00 ES, and 3.00 ES

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
zsh: abort (core dumped)  ./build/src/zutty

# Cheeky
% MESA_GLES_VERSION_OVERRIDE=3.3 ./build/src/zutty
E [charvdev.cc:181] Error: Compiling compute shader:
0:3(1): error: local_size_x exceeds MAX_COMPUTE_WORK_GROUP_SIZE (0)

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
zsh: abort (core dumped)  MESA_GLES_VERSION_OVERRIDE=3.3 ./build/src/zutty
```

**Comment by arodland** [comment]
Probably related: when I build and run zutty on my machine, it builds fine, but errors with

```
zutty: ../src/main.cc:174: void make_x_window(Display*, EGLDisplay, const char*, int, int, Window*, void**, void**): Assertion `val == 2' failed.
Aborted (core dumped)
```

on adding a debug print, I find that `eglQueryContext (egl_dpy, ctx, EGL_CONTEXT_CLIENT_VERSION, &val)` populated `val` with 3, while the expected value is 2, so this seems like a version mismatch that isn't even detected by appropriate runtime code, let alone compile time.

**Comment by tomszilagyi** [comment]
Hi!

Thanks for trying Zutty! This program is still fairly new, not many people have used it yet, so there might be issues and feedback is welcome.

@Earnestly I believe the actual support level of the OpenGL (ES) implementation is only detectable at runtime, i.e., having the right EGL and GLES libraries to compile with (which is what the configure script is able to check) does not guarantee that the OpenGL implementation available supports the required level (this depends on the exact graphics hardware in use / selected if you have more than one). Arguably, the error message could be more "user friendly", albeit `error: GLSL ES 3.10 is not supported. Supported versions are: 1.00 ES, and 3.00 ES` is pretty clear IMO.

@arodland Duplicate of #3, there is a fix pending for that, please be patient (I only have time to do integration testing and publish updates on weekends).

**Comment by Earnestly** [comment]
The purpose of a `configure` phase, in part, is to compile and execute small programs that do these checks.  A warning during configure is what I suggested, not an error due to it being runtime dependent.

I haven't suggested that the error during runtime after it has been compiled is an issue.

**Comment by tomszilagyi** [comment]
@Earnestly Thanks for clarifying.

To me, the purpose of the configure phase is to establish whether it is possible to compile the program in the current environment, and if yes, with what settings. The question of whether the built program can or cannot run (on the same machine or on a different one) is tangential (and as evident in the case of an OpenGL application, non-trivial).

In your concrete case, you are getting a clear indication that your graphics hardware does not support OpenGL ES 3.1. Yes, you get this at runtime -- you could (at least in theory) upgrade your video hardware or move the binary you built to a different machine (with the same machine type etc.) and successfully run it.

Were this to be reported at the configure stage, that could be potentially misleading for the above reasons. It could be a warning, yes, but at the expense of greater complexity (a separate test program: a mini-Zutty to see if you can run the real Zutty!) and longer runtime (mini-Zutty has to be built), and providing (in my opinion) exactly zero value. If your hardware is not suited to run Zutty, you are going to find that out pretty quickly anyway.

The only tangibly useful (currently missing) thing I can see at this point is a FAQ entry about this. (There is no FAQ yet.)

**Comment by Earnestly** [comment]
You've just repeated what I've already pointed out.  I wasn't clear at all and this isn't going anywhere.

**Comment by eebssk1** [comment]
> @DeathSlicer999 Given you already know that your platform (VM) does not have the required level of accelerated graphics support, what solution do you want? (I assume you have read the FAQ as well.)

I tried in virtualbox 7.0.13 beta with 3D accel on, and it crashes with `Error: Compiling compute shader`.
This is initially confusing to me because Debian 12 with XFCE sets zutty as the default terminal emulator (instead of the one that comes with XFCE), and it just disappears immediately when starting from the dock.
If you want, you can consider a fallback to software rendering with Mesa in such a situation.
