### ISSUE TITLE
core dumped on Arch Linux

### ISSUE THREAD

**Issue by chromer030** [tomszilagyi/zutty#56]
E [charvdev.cc:215] Error: Compiling fragment shader:
0:1(10): error: GLSL ES 3.10 is not supported. Supported versions are: 1.00 ES, and 3.00 ES

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
[1]    28360 abort (core dumped)  zutty

**Comment by tomszilagyi** [comment]
Read the FAQ
