### ISSUE TITLE
last column+wrap pending subtleties

### ISSUE THREAD

**Issue by ninjalj** [tomszilagyi/zutty#57]
On VTxxx terminals, controls which potentially move out of the last column are supposed to reset the Last Column Flag (see page D-13 of DEC STD-070). Some info and test results at https://github.com/mattiase/wraptest

At https://invent.kde.org/utilities/konsole/-/merge_requests/510#note_326117 there is a test script that writes `A<something>B` at the last column. The results of this test script differ for zutty in the following cases:

 - A<CUD 1>B
   - shows A at the last column, B at the next line's last column.
   - on zutty, just shows A at the last column.
 - A<CUU 1>B
   - shows A at the last column, B at the previous line's last column.
   - on zutty, just shows A at the last column
 - AB with AutoWrap Mode off:
   - shows B at the last column.
   - on zutty, shows A at the last column.
 
With Auto Wrap Mode off, writing past the last column results in overwriting the last column on VT100+ terminals. This was also true on the Teletype Model 33, from "574-122-100TC - Typing Unit Operation, M. Spacing Mechanism, 4.77":

> At the end of the printed line, spacing is suppressed and the typing unit overprints.

**Comment by tomszilagyi** [comment]
Many thanks for reporting this!
I will incorporate your test script as well as the 'wraptest' report generator into the test suite.
With the bugs fixed of course :)
