### ISSUE TITLE
Support for not only GLSL ES 3.00, but also GLSL ES 3.1.0

### ISSUE THREAD

**Issue by xyproto** [tomszilagyi/zutty#58]
When starting `zutty 0.10` on a mac mini with Intel graphics that runs Arch Linux, I get:

```
E [charvdev.cc:215] Error: Compiling fragment shader:
0:1(10): error: GLSL ES 3.10 is not supported. Supported versions are: 1.00 ES, and 3.00 ES

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
zsh: abort (core dumped)  zutty
```

**Comment by tomszilagyi** [comment]
What does `zutty -glinfo` say?

**Comment by xyproto** [comment]
Here it is: [glinfo.txt](https://github.com/tomszilagyi/zutty/files/7741725/glinfo.txt)

**Comment by tomszilagyi** [comment]
`GL_VERSION      = OpenGL ES 3.0 Mesa 21.3.1`

Compute shader support appeared in OpenGL ES 3.1.
