### ISSUE TITLE
support application keypad

### ISSUE THREAD

**Issue by kilobyte** [tomszilagyi/zutty#60]
The application keypad mode (`\e=`) doesn't work yet.  Without it, a whole 20% of a full-sized keyboard is redundant (vs either digits or arrows).  Not many programs make use of this mode, but I for one have a need for it.

**Comment by tomszilagyi** [comment]
The keyboard support of Zutty is extensively documented, see https://tomscii.sig7.se/zutty/doc/KEYS.html
Based on this, DECKPAM (`ESC =`) should work, look no further than the first table.
Further, Zutty passes the keyboard tests of VTTEST, so I think things work pretty well.

If you want me to look into this, please submit an actual bugreport. Like:
0. what is your platform and your environment?
1. what exactly are you doing with Zutty?
2. what exactly do you get/see?
3. what exactly did you expect, based on what?
4. why is your expectation correct and not what you got?
5. what other terminals do you use, where this works as you expect?

You can use something like `cat -vT` to investigate exactly what the emulator is sending to the shell in response to some keypress (which is essentially what is documented on the link posted above).

**Comment by kilobyte** [comment]
Seeing that your documentation describes output in cursor mode as `8` `4` `6` `2` rather than `\e[A` `\e[D` `\e[B` `\e[C` I now see what's wrong.  Zutty reports correct codes only when NumLock is on, the issue happens only with NumLock off.

**Comment by kilobyte** [comment]
All other terminals (that support application mode at all) let NumLock affect only cursor mode.

**Comment by tomszilagyi** [comment]
By `8` `4` `6` `2` are you referring to the modifier codes as in the second table?
There is no explicit handling of NumLock anywhere in Zutty (as far as I remember off the top of my head).
Which does not mean it can't be necessary to add it somewhere.

Can you give me a *complete* and *minimal* example of how I can test for the correct behaviour?

**Comment by kilobyte** [comment]
Sure, just have NumLock off, and type `printf '\e=';cat -vT` then press keypad arrow keys.

On rxvt, Linux console, ..., I get: `^[Ox^[Ot^[Ov^[Or`, on zutty: `^[[A^[[D^[[C^[[`

**Comment by tomszilagyi** [comment]
Thanks!
Have you tried this with xterm? Because (at least for me, here and now) that produces identical results to zutty, and I consider xterm to be authoritative.

**Comment by kilobyte** [comment]
xterm has different personalities, and defaults to emulating Sun rather than vt100.  To switch to vt100 (vt220 to be exact) mode, the incantation is: `\e[?1051l\e[?1052l\e[?1060l\e[?1061h` (only the first enabled personality matters, thus you need to disable all lower-numbered ones).

zutty doesn't implement modes other than vt100 and vt52 (it says so on its controlling terminal), and neither do rxvt or Linux.

Once you switch xterm to vt220, it works as expected.

**Comment by tomszilagyi** [comment]
> it says so on its controlling terminal

I don't follow this, where/how does this happen?

**Comment by kilobyte** [comment]
```
W [vterm.icc:1469] (Unimplemented) reset priv mode 1051
W [vterm.icc:1469] (Unimplemented) reset priv mode 1052
W [vterm.icc:1469] (Unimplemented) reset priv mode 1060
W [vterm.icc:1423] (Unimplemented) set priv mode 1061
```

**Comment by kilobyte** [comment]
Other terminals also silently ignore these xterm-private modes, thus I just output the xterm mode sequence unconditionally.

**Comment by tomszilagyi** [comment]
Oh, I see. Thanks for clarifying :)

So if I understand correctly, you are essentially arguing that the vt220 mode is the "correct" one and that should be the default way for Zutty to interpret keys.

If so, why? As opposed to the current state, where Zutty produces identical results to xterm's default settings?

You haven't told me what your use case is, i.e., what you are actually trying to achieve / what program you actually use and how that is broken in Zutty compared to (say) rxvt. While I am all for fixing clear-cut fundamental correctness issues as much as anyone, here I sense that we are coming down to something less exact. So I would like to know more about the actual issue that affects you.

**Comment by kilobyte** [comment]
Well, you claim to support vt100 mode :)  As for xterm, it has a history as mostly Sun-centric software (with support for other ancient commercial Unices), thus its defaults are quite specific.  Its language is also different contrary to the rest of the world, common sense included (see eg. `\e[21m` doing wavy underline rather than disabling `\e[1m` like all other codes in the 20s range do — other terminals switched to xterm ways only a few years ago).

But philosophical reasons aside, it doesn't matter what the xterm default is, as long as any program that wants the application mode can just emit a slightly longer sequence.  This works with xterm, doesn't with zutty.

Another reason is, if application mode is ignored when NumLock is off, we get two redundant arrow blocks sending the same codes and thus being indistinguishable by the program (thus a waste of keyboard space!).  In theory, the user could toggle NumLock, but as NumLock state is global while application-vs-cursor mode local to a terminal, any other terminal switched to will suddenly start producing digits where arrows are expected.

**Comment by kilobyte** [comment]
As for use case: my direct use case at the moment is playing MUDs — where you type text while rapidly moving your character around.  These are fast-paced games that require typing multiple long lines per second; obviously people heavily use shortcuts to get things done.  The keypad arrows are bound to `nw`/`n`/`ne`/`w`//`e`/`sw`/`s`/`se` while "grey" arrows are used for shell-like editing the command line.

Same applies to spreadsheet and form input: you use keypad arrows to navigate to a different field while using "grey" arrows for editing inside the field.

**Comment by tomszilagyi** [comment]
> Well, you claim to support vt100 mode :) 

With the tacit exception that if xterm (which I consider its modern successor) does something differently by default, then zutty will follow that behaviour instead of vanilla vt100. But you are right in that xterm has a control sequence to switch to vt220 input mode, and this is currently not implemented by zutty.

> As for xterm, it has a history as mostly Sun-centric software (with support for other ancient commercial Unices), thus its defaults are quite specific. Its language is also different contrary to the rest of the world, common sense included (see eg. `\e[21m` doing wavy underline rather than disabling `\e[1m` like all other codes in the 20s range do — other terminals switched to xterm ways only a few years ago).

According to xterm's control sequences documentation (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) `\e[21m` turns on doubly-underlined (with reference to ECMA-48, so I don't quite get your reference about being "contrary to the rest of the world" and wavy underlines here). But I'm not here to defend xterm, and I digress...

> 
> But philosophical reasons aside, it doesn't matter what the xterm default is, as long as any program that wants the application mode can just emit a slightly longer sequence. This works with xterm, doesn't with zutty.

Yes, as I mentioned above, for practical reasons zutty tries to behave like a more-or-less vanilla xterm.
And the vt220 keyboard mode is not implemented by zutty.
I can possibly implement it in the future.

**Comment by kilobyte** [comment]
My point is, a vanilla xterm can be switched to application mode without any user-visible differences — the program has to emit `\e=` at least, there's no extra cost in emitting something xterm-specific that's silently ignored by others.

You also already diverge from xterm here: it doesn't support the application mode at all when in the default Sun mode.

|  | NumLock on | NumLock off |
| - | - | - |
| rxvt/Linux | ^[Ox^[Ot^[Ov^[Or | ^[Ox^[Ot^[Ov^[Or |
| xterm [Sun] | 8462 | ^[[A^[[D^[[C^[[B |
| xterm [vt220] | 8462 | ^[Ox^[Ot^[Ov^[Or |
| zutty | ^[Ox^[Ot^[Ov^[Or | ^[[A^[[D^[[C^[[B |

**Comment by tomszilagyi** [comment]
Feel free to test this patch (the first hunk is only for debugging if you want to check the keysyms received by zutty).
[app_keys_60.patch.txt](https://github.com/tomszilagyi/zutty/files/7789999/app_keys_60.patch.txt)

**Comment by kilobyte** [comment]
Awesome, it works for me!  All the keypad keys return codes I'd expect.

**Comment by tomszilagyi** [comment]
Great, thanks!

There is one small discrepancy remaining wrt xterm and that is with NumLock on, the non-digit keys (/ * - +) generate control sequences instead of their own literals. This is because the keysyms generated by X do not differ depending on the state of NumLock, as opposed to the other numpad keys where they do (for example, `XK_KP_8` vs `XK_KP_Up`). So I need to start actually looking at the state of NumLock as part of computing the key translation. Will include that as well (plus tests/docs updates) in the committed fix.

But you already have what you need so you don't have to wait any longer :)

**Comment by kilobyte** [comment]
I'm not sure if you need to preserve xterm behaviour that strictly, when other terminals don't care about NumLock state here.  Less work for you in this case.

But hey, for me having NumLock on is a heresy (and the other kind of folks likewise never press it more than once per session), thus I don't really care.

Mighty thanks!
