### ISSUE TITLE
Ctrl-[  + Vim partial escape sequence

### ISSUE THREAD

**Issue by softmoth** [tomszilagyi/zutty#61]
## Problem behavior

Typing `^[` (*Ctrl* + *Left bracket*) in Vim when in *Insert* mode inserts the number `3`. It should behave the same as `Esc`.

## Details

When in *Insert* mode,
- `^V^[.` produces `^C.`
- `^V^[^[.` produces `!.`
- `^V^[^[^[` produces `ÿ`

Typing `Esc` works as it should in all cases. Using `xterm`, `urxvt`, `xfce4-terminal`, etc. works as it should.

This does not happen in other programs, such as `vi` (version 4.0 (gritter) from ex-vi.sourceforge.net) or `cat -v`. Here pressing `^[` is indistinguishable from `Esc`.

This test user has no `.vimrc`, and no Zutty-related settings in *xrdb*:
- `env`: [jdoe-env.txt](https://github.com/tomszilagyi/zutty/files/7829802/jdoe-env.txt)
- `xrdb -query`: [jdoe-xrdb.txt](https://github.com/tomszilagyi/zutty/files/7829803/jdoe-xrdb.txt)

## Zutty output

This is the output from running `zutty -verbose`, and then `vim<CR>:q!<CR>vim<CR>i^[^V^[.^V^[^[.^V^[^[^[<Esc>:q!<CR>^D`.

Zutty does not print any debug messages while I'm typing. The six messages (W, W, W, W, E, W) all print as Vim is starting up.

```
Zutty 0.9-dirty
Copyright (C) 2020 Tom Szilagyi

This program comes with ABSOLUTELY NO WARRANTY.
Zutty is free software, and you are welcome to redistribute it
under the terms and conditions of the GNU GPL v3 (or later).

I [font.cc: 55] Loading /usr/share/fonts/misc/9x18.pcf.gz as primary
I [font.cc:199] Glyph size 9x18
I [font.cc: 55] Loading /usr/share/fonts/misc/9x18B.pcf.gz as overlay
I [font.cc:199] Glyph size 9x18
I [main.cc:169] Window ID: 10485762 / 0xa00002
I [charvdev.cc:413] Resize to 1278 x 1574 pixels, 141 x 87 chars
W [vterm.icc:1399] (Unimplemented) Start blinking cursor
W [vterm.icc:1449] (Unimplemented) Stop blinking cursor
W [vterm.icc:1623] (Unimplemented) attribute: 29
W [vterm.icc:1729] (Unimplemented) DCS: 'zz'
E [vterm.icc: 91] Error: Unhandled input char '%' (37) in state CSI. Escape sequence so far: '\e[0%' (4 bytes)
W [vterm.icc:1623] (Unimplemented) attribute: 29
W [vterm.icc:1399] (Unimplemented) Start blinking cursor
W [vterm.icc:1449] (Unimplemented) Stop blinking cursor
W [vterm.icc:1623] (Unimplemented) attribute: 29
W [vterm.icc:1729] (Unimplemented) DCS: 'zz'
E [vterm.icc: 91] Error: Unhandled input char '%' (37) in state CSI. Escape sequence so far: '\e[0%' (4 bytes)
W [vterm.icc:1623] (Unimplemented) attribute: 29
```

### My environment

zutty 0.9-dirty from Manjaro Linux community/zutty-0.10-1, Vim 8.2.3582, i3 version 4.20.1.

**Comment by tomszilagyi** [comment]
Thank you for the meticulous report, this is exactly how everyone should write them!
Can you please test the attached patch to verify that it solves all related issues: [ctrl_brackets_61.patch.txt](https://github.com/tomszilagyi/zutty/files/7830171/ctrl_brackets_61.patch.txt)

**Comment by softmoth** [comment]
Yes, it does fix it (tested w/ HEAD).

It also fixes another symptom I hadn't reported: with my fancy Zsh prompt, after I'd exit Vim the cursor was placed one cell to the left of where it ought to be. I.e., instead of ` 13:58  ~/g/zutty  ` it displayed ` 13:58  ~/g/zutty `. Hitting `^L` refreshed the screen but didn't restore the missing space. Hitting `Enter` produced a new prompt with the space as expected. I report it just in case someone else reports something similar; it's fixed for me with your patch.

Thanks!
