### ISSUE TITLE
Box drawing alignment on scalable font

### ISSUE THREAD

**Issue by softmoth** [tomszilagyi/zutty#62]
Characters are misaligned when using a scalable font. In this screenshot, XTerm is on top and Zutty is below.

1. Horizontal and vertical alignment is off, so pieces don't connect.
2. Scaling is inaccurate, leading to a 1px gap between horizontal lines. (XTerm struggles, too, but in the vertical dimension with this particular font.)
3. Possibly related, there appears to be a pixel of padding missing from the top. This is nitpicking, but it does make text look like it's floating up towards the ceiling. I mention it here in case it's related to some alignment math and might be a clue.

I used `zutty -font DejavuSansMono -fontsize 18` and `xterm -fa 'Dejavu Sans Mono' -fs 8.5`, which gets the two pretty close in size on my screen.

Using `zutty -font DejavuSansMono -fontsize 20` does make the box drawing characters line up correctly.

Using Kitty aligns everything correctly (and with solid lines both vertical and horizontal) at all font sizes. `kitty -o font_family='Dejavu Sans Serif' -o font_size=8.5`.

None of these issues show on `zutty -font 9x18`.

I have `Xft.dpi: 144` in `.Xresources`. It appears that Zutty does not respect that in the same way as XTerm, Kitty, and other applications do.

![alignment example](https://user-images.githubusercontent.com/774788/148617345-43471b38-b6f8-48fe-b067-495df33f0f48.png)
![line height comparison](https://user-images.githubusercontent.com/774788/148631208-2c399325-4472-44c3-96a8-60312c3d3de3.png)

**Comment by tomszilagyi** [comment]
Acknowledged.
Looks like I need to revisit some code in the font glyph atlas builder.
As a heads up, there are roundings inherent to rasterizing the scaled font to any integer size, so a perfect result might not be achieved (as seen with xterm).
Nevertheless, I hope to improve on the current state (which is not great, as you have amply demonstrated).

**Comment by tomszilagyi** [comment]
I closed this ticket as I now consider the quality of support for scaled fonts on par with xterm (and I do not have any goals to go beyond that level, as zutty is mostly geared towards bitmap fonts). Feel free to reopen with updated evidence if you disagree.

**Comment by softmoth** [comment]
I do think the box-drawing misalignment is a significant issue, but I understand that scaled fonts are not a priority. I've found a bitmap font that's suitable for my screen resolution, and I'm OK with this being ruled out of scope for the your project.
