### ISSUE TITLE
clickable urls

### ISSUE THREAD

**Issue by bbbart** [tomszilagyi/zutty#72]
I recently switched to Zutty (coming from Alacritty) and am *very* happy with my new terminal. The only thing I seem to be missing a few times every day, are clickable URLs, for example in `mutt` or other TUIs.

Is this something Zutty is planning to support? Or supports already perhaps? Or should I look elsewhere to enable this feature (using a multiplexer, for example?).

Thanks!

**Comment by tomszilagyi** [comment]
Hello and welcome!

Clickable URLs are not supported and this is not really a planned feature either, unless I see overwhelming demand for it (you are the first to ask).

Hint: an URL, email address or similar that is surrounded by spaces can be selected by double-clicking on it. (Double-clicks trigger selection snap-to-word, 'word' defined as the longest contiguous block of characters without whitespace.) Then you can paste it into your browser window right away.

**Comment by bbbart** [comment]
Thanks for the quick reply!

Yes, I'm aware of the snapping selection features. It's not really a workaround for me personally, as that workflow is far heavier than simply clicking (also involves focusing a different window, etc...).

However, in my most common scenario's, I'm using `tmux` anyway, so I'm relying on a plugin there to quickly open URLs into browser tabs for now.

Thanks!
