### ISSUE TITLE
User -title is ignored when using -e option

### ISSUE THREAD

**Issue by mones** [tomszilagyi/zutty#75]
Hi Tom,
Just found that trying to title a window which is launching another program with -e doesn't work as expected.
The attached zipped patch fixes it for me. Unzip and apply with git am :smile:
Thanks in advance!

[0001-Honor-title-set-by-user-when-e-is-used.zip](https://github.com/tomszilagyi/zutty/files/8645718/0001-Honor-title-set-by-user-when-e-is-used.zip)

**Comment by mones** [comment]
Hi again: forgot to say that the above patch doesn't work when user sets title to "Zutty", because it would be the same as default. Supporting that corner case would complicate things, so not sure is worth the effort, specially when adding some char (e.g.: -title " Zutty ") can easily workaround this limitation.

**Comment by tomszilagyi** [comment]
Hi,
It is intentional that -e sets the title to the command being run. It is even documented, check the description for -title at https://tomscii.sig7.se/zutty/doc/USAGE.html#Basic%20configuration%20and%20mode%20switches

**Comment by ttrei** [comment]
From my perspective, the title set by -title should have higher precedence, since it is an explicit user choice.

My use case is window identification in a script that asynchronously launches some programs and moves the resulting windows to their intended workspaces in i3-wm. Windows may appear in arbitrary order, and I haven't found a better way to identify them.

**Comment by mones** [comment]
> Hi, It is intentional that -e sets the title to the command being run. It is even documented, check the description for -title at https://tomscii.sig7.se/zutty/doc/USAGE.html#Basic%20configuration%20and%20mode%20switches

Yeah, I have no problem with -e setting title to the command being run if no other option is set, it's a good idea/feature. But if the user requests a different one via the -title option there's a conflict. The usual way to solve that conflict is that, unless there's a good reason not to, explicit user requests should be honored over default behaviors, as @ttrei said.

That phrase in the docs could also be updated to something similar to:

[...] It also sets the window title to the basename of the program to be executed, _unless explicitly set with the -title option._

I can provide another patch with all the changes if you prefer, just let me know.
