### ISSUE TITLE
Patch to fix build on Debian kFreeBSD and Hurd architectures

### ISSUE THREAD

**Issue by mones** [tomszilagyi/zutty#77]
Hi Tom,

I'm already using it on current packaging, but I think you could be interested in adding it to zutty codebase:
https://salsa.debian.org/debian/zutty/-/blob/master/debian/patches/10_fix_FTBFS_kfreebsd_and_hurd.patch

best regards,

**Comment by tomszilagyi** [comment]
I don't have anything agains this. More platforms to the people!
