### ISSUE TITLE
Zutty on KMS/DRM?

### ISSUE THREAD

**Issue by vanfanel** [tomszilagyi/zutty#79]
Hi!

Since Zutty seems to be tailored for low-end systems, I was wondering if it would be possible to make it work on X-less systems.
SDL2 and Retroarch work on KMS/DRM for low-latency, which makes most GNU/Linux games run on such an enviroment with no problems at all.

That way, Zutty could be a proper accelerated TTY terminal, something thaat GNU/Linux distros really need.

**Comment by tomszilagyi** [comment]
Nice idea, could be done (at least in theory) given that the architecture of Zutty is nicely separated (the Vterm class has no knowledge of X whatsoever - the main module handles and dispatches X events; that would need to be rewritten for interfacing to a different external API, but the terminal core would stay intact). Selections would also need a different interface (if there is an API at all, not sure).

**Comment by vanfanel** [comment]
@tomszilagyi I am willing to pay for this to happen, because it would fulfill a dream of mine and I don't know Zutty's internals.

Would you accept a donation with no hurries?
I am not a coder anymore...

**Comment by tomszilagyi** [comment]
@vanfanel Sorry but no, see the [FAQ](https://github.com/tomszilagyi/zutty/wiki/FAQ#q-can-i-donate--sponsor--pay-you-to-support-the-development-of-zutty-can-i-incentivize-work-on-certain-bugs-or-features).

The internals of Zutty are well structured and reasonably [documented](https://tomscii.sig7.se/zutty/doc/HACKING.html#Module%20breakdown), it is a small program, any professional programmer should be able to find his/her way around it. Anyone is free to fork it and implement anything as long as they respect the copyleft license on it.

**Comment by vanfanel** [comment]
@tomszilagyi Then what would be the way to get it done? By doing it myself?
