### ISSUE TITLE
inconsistent Ctrl/Alt-Kpad

### ISSUE THREAD

**Issue by kilobyte** [tomszilagyi/zutty#81]
Your [documentation](https://tomscii.sig7.se/zutty/doc/KEYS.html#Sequences%20dependent%20on%20keypad%20mode%20setting) explains how modifier keys (Ctrl, Alt, Shift) interact with keypad keys when in VT100 App mode.

However, only `KpadSlash` `KpadMultiply` `KpadMinus` `KpadPlus` `KpadEnter` `KpadDot` work as described.  `Kpad9` `Kpad3` `Kpad0` ignore any modifiers, while `Kpad7` `Kpad8` `Kpad4` `Kpad5` `Kpad6` `Kpad1` `Kpad2` return modifiers with non-App mode values.

**Comment by tomszilagyi** [comment]
Yeah, looks like things are a bit off in the keypad mapping dept.
Stay tuned for a fix.
