### ISSUE TITLE
SourceCodePro segfault

### ISSUE THREAD

**Issue by collin-kemper** [tomszilagyi/zutty#86]
Whenever I run `zutty -font SourceCodePro -fontsize 40`, I get the following:
```
Warning: non-UTF-8 locale: C
Expect broken international characters (or fix your locale)!
zsh: segmentation fault (core dumped)  zutty -font SourceCodePro -fontsize 40
```

I have Adobe's SourceCodePro font installed and don't know why it segfaults. Files are `.otf` files, not sure if that is the source of the issues.

**Comment by tomszilagyi** [comment]
Thanks for reporting. This will be fixed soon - stay tuned!

(The warning about your locale is an entirely separate thing, you should fix that if you care about non-ascii characters, I recommend a setting of `LANG=en_US.UTF-8`.)
