### ISSUE TITLE
Double free or corruption error on start

### ISSUE THREAD

**Issue by OchreRed** [tomszilagyi/zutty#89]
Exact error:
```
$ zutty
double free or corruption (out)
Aborted
```
Platform: Void Linux, Linux version 5.18.19_1
How I encountered this issue:
1. I installed Zutty using `sudo xbps-install zutty` on Void Linux
2. I opened Zutty and changed a config file.
3. I changed my ~/.Xresources file, changing Zutty.font to Hasklig and Zutty.fontsize to 18.
4. I exited Zutty.
5. I then tried opening Zutty again from the terminal, and I got a double free or corruption error.
Here is my ~.Xresources file copy-pasted: http://0x0.st/of47.c
Most of the settings aren't related to Zutty.
Please let me know if providing any other information would be helpful.

**Comment by tomszilagyi** [comment]
I believe this is a duplicate of #86, stay tuned for a fix
