### ISSUE TITLE
support both clipboard and primary

### ISSUE THREAD

**Issue by anarcat** [tomszilagyi/zutty#9]
> Zutty can be configured to use whichever selection target you prefer (it defaults to the PRIMARY selection, but you might want to use CLIPBOARD instead).
>
> Zutty faithfully replicates what xterm has provided for a very long time: starting selections with the left button, adjusting them with the right button, and cycling between snap-to-char/word/line with double clicks. Compared with xterm, one notable difference is a built-in, simpler rule for word boundaries (as opposed to user-adjustable definitions of character classes).
> 
> Paste the selection into the terminal via middle click or Shift-Insert, like in xterm.

If I understand correctly, you can configure zutty to copy things to EITHER the PRIMARY selection or CLIPBOARD, it's a configuration thing. It's great that it supports this traditional approach, but I think it misses a key, powerful point of the multiple "clipboard" functionality X has: the possibility of having *two* selections carried over between apps at once.

In urxvt, right now, for example, i can do this:

 1. select a username
 2. <kbd>control-shift-c</kbd>
 3. select the password
 4. go to another app
 5. paste the username with <kdb>control-shift-v</kbd>
 6. paste the password with middle mouse button

This avoids a back-and-forth between the two apps! Could this be supported in zutty as well? Basically, the idea is that the PRIMARY selection is managed by the mouse selection, but the CLIPBOARD is managed by the less-traditionnal, maybe-evil-because-it-comes-from-Apple? <kbd>control-x-c-v</kbd> thing. :)

thanks, great project!

**Comment by tomszilagyi** [comment]
I understand your usecase perfectly well, and in theory, yes, this could be supported. I can even see that this could be practical for a number of users. That said, what if you want to copy three different things? Or four? To me it feels like a special case (probably because I've never done this).

As a person who has looked at lots of different terminals (probably much more than I have), can you list the terminals that have this feature? I'm curious to see how widespread this is.

**Comment by anarcat** [comment]
> That said, what if you want to copy three different things? Or four? To me it feels like a special case (probably because I've never done this).

Then you have an extra roundtrip, sure. But the two-fold "performance increase" is great. (also there *are* more than two selection buffers in X, so one could argue you could grant access to those as well ;))

> As a person who has looked at lots of different terminals (probably much more than I have), can you list the terminals that have this feature? I'm curious to see how widespread this is.

I suspect all libvte terminals have this feature, because they support copy-paste through the clipboard and "selecting text" also does the right thing. urxvt needs a little wrangling to use the right shortcut (and maybe even a perl plugin), but it also works. xterm doesn't, obviously.

i suspect it's basically "everything but xterm".

**Comment by tomszilagyi** [comment]
Thanks! Yeah, there are X cut buffers as well (0-9). But not everything out there needs to be supported :)
I will leave this issue open so I have some reminder (but don't hold your breath)

**Comment by anarcat** [comment]
> Yeah, there are X cut buffers as well (0-9).

I meant SECONDARY, actually, i did not know about those cut buffers until now! :) But yeah, don't bother with SECONDARY, but I do think that having a shortcut for accessing the clipboard would respect the Principle Of Least Astonishment... 

Some pointers:

 * [JWZ](https://www.jwz.org/doc/x-cut-and-paste.html) - mentions cut buffers, clipboard, primary
 * [vain](https://www.uninformativ.de/blog/postings/2017-04-02/0/POSTING-en.html) - mentions clipboard, primary, secondary, includes code samples
 * [ICCM spec, section 2.6.1](https://tronche.com/gui/x/icccm/sec-2.html#s-2.6.1) - mentions clipboard, primary, secondary
 * [freedesktop](https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt) - mentions clipboard, primary, secondary (described as "no one does anything interesting" with), clearly indicates "PRIMARY is an "easter egg" for expert users"

The freedesktop spec, in particular, has fairly clear guidelines on how this should work:

> Application authors should follow the following guidelines to get
> correct behavior:
> 
>  - selecting but with no explicit copy should only set PRIMARY,
>    never CLIPBOARD
> 
>  - middle mouse button should paste PRIMARY, never CLIPBOARD
> 
>  - explicit cut/copy commands (i.e. menu items, toolbar buttons)
>    should always set CLIPBOARD to the currently-selected data (i.e.
>    conceptually copy PRIMARY to CLIPBOARD)
> 
>  - explicit cut/copy commands should always set both CLIPBOARD and
>    PRIMARY, even when copying doesn't involve a selection (e.g. a
>    "copy url" -option which explicitly copies an url without the
>    url being selected first)
> 
>  - explicit paste commands should paste CLIPBOARD, not PRIMARY
> 
>  - a selection becoming unselected should never unset PRIMARY
> 
>  - possibly contradicting the ICCCM, clients don't need to support
>    SECONDARY, though if anyone can figure out what it's good
>    for they should feel free to use it for that
> 
>  - cut buffers are evil; they only support ASCII, they don't 
>    work with many clients, and they require data to be 
>    copied to the X server. Therefore clients should avoid 
>    using cut buffers and use only selections.

So that's what I got. At least if you follow this path you can claim to conform with some spec now! ;)

>  I will leave this issue open so I have some reminder (but don't hold your breath)

Sure, thanks for keeping it open! :)

**Comment by anarcat** [comment]
oh, and if you ever think of porting this to wayland, it's a whole other can of non-standard worms, of course. some pointers:

 * https://wayland-book.com/clipboard.html - yes, that is an empty page. just shows.
 * https://wiki.gnome.org/Initiatives/Wayland/PrimarySelection - they didn't want PRIMARY, but they ended up adding it anyways
 * https://github.com/swaywm/sway/issues/1012 - same with sway
 * https://bugreports.qt.io/browse/QTBUG-66008 - and QT
 * https://github.com/bugaevc/wl-clipboard - copy-paste tool for wayland

It's all a bit of a mess.

**Comment by anarcat** [comment]
ah, and sorry for the multiple messages, but if i may make one last argument... the rest of the world does use the PRIMARY and CLIPBOARD distinction. if you "copy" in your web browser (e.g. those little "clipboard" buttons you see in websites) , it goes to CLIPBOARD. if you set zutty to only talk to PRIMARY, you are basically unable to copy-paste from Firefox. inversely, if you set it to CLIPBOARD in zutty, then you don't get the magic middle-button trick. it seems like the worst of both worlds to me. ;)

**Comment by tomszilagyi** [comment]
For the record, xterm can also be configured to behave exactly this way. The PRIMARY selection is used by default (for selection and pasting by middle button) unless `selectToClipboard` is set (that is off by default), so no change needed there. To add key bindings for accessing the CLIPBOARD selection, add this to your `~/.Xresources`:

```
XTerm*vt100*translations:      #override \n\
                               Ctrl Shift <Key>C:  copy-selection(CLIPBOARD) \n\
                               Ctrl Shift <Key>V:  insert-selection(CLIPBOARD)
```

(and do the obligatory xrdb merge so it takes effect)

**Comment by anarcat** [comment]
amazing. will definitely add this to my Xresources right now, at least. one of the main reasons why i'm on rxvt!!

and thanks for implementing this, will go a long way into adoption, imho!
