### ISSUE TITLE
The design of viewOffset

### ISSUE THREAD

**Issue by ericwq** [tomszilagyi/zutty#92]
First, thanks for this project and the design document. It help me a lot to understand the terminal design and implementation.

From the [design document](https://tomscii.sig7.se/zutty/doc/HACKING.html#Frame), it says:

`
Given the above defined memory layouts, it is easy to see how the screen can be directed to display something other than the active area. The view position is defined by a single row offset viewOffset that can take values from 0 (display the active area) up to and including saveLines (display the top of history).
`

I checked the source code and performed some test, but it's not easy for me to understand what the `viewOffset` stand for.
https://github.com/tomszilagyi/zutty/blob/b7bc75148a0a15eda4f9b5437941949cf72ef5bd/src/frame.icc#L232
especially, the following part:
```c++
   Frame::getPhysicalRow (int pY) const
   {
      if (pY < 0)
      {
         if (!margins)
            pY += scrollHead;
         if (pY < 0)
            pY += nRows + saveLines;
         return pY;
      }

      if (margins && (pY < marginTop || pY >= marginBottom))
         return pY;

      pY += scrollHead - marginTop;
      if (pY >= marginBottom)
         pY -= marginBottom - marginTop;

      return pY;
   }
```
Could you give me a detail explanation about `viewOffset`?

**Comment by tomszilagyi** [comment]
There is no `viewOffset` in the code you refer to. What you are looking at is the code dereferencing a row in the circular buffer internal to the Frame. I believe the excerpt regarding `viewOffset` (that you pasted above) says it all.

**Comment by ericwq** [comment]
Sorry, I only refer to the `getPhysicalRow()` in the previous post. Next, I try to make my question clear.


`getViewRowPtr()` calls `getPhysRowPtr()`, `getPhysRowPtr()` calls `getPhysicalRow()`, with a negative integer parameter (`pY - viewOffset`), `getPhysicalRow()` calculates the physical row based on the above parameter. `getPhysicalRow()` uses `scrollHead` to calculate the row number if margin is not set.

My question is : I can't figure out the relationship between `viewOffset` and `scrollHead`.

```c++
   inline const CharVdev::Cell *
   Frame::getPhysRowPtr (int pY) const
   {
      return & operator [] (nCols * getPhysicalRow (pY));
   }

   inline const CharVdev::Cell *
   Frame::getViewRowPtr (int pY) const
   {
      return getPhysRowPtr (pY - viewOffset);
   }
```

**Comment by tomszilagyi** [comment]
Not sure what kind of relationship are you looking for? `viewOffset` is how many rows the view is offset by the user jumping back above. 0 = normal state, 10 = we are looking at history starting from the 10th line above the currently visible top of screen, plus the remaining "visible" part (without the last 10 lines of course), if `viewOffset` happens to be less than `nRows`. `scrollHead` is an internal pointer in the frame's circular buffer. Of course if you want to get at a certain row in the current view which is what `getViewRowPtr` does, then you will look at a "physical row" by offsetting with the `viewOffset`, which in turn will take the `scrollHead` into account in some way.

Re. your second question: `nRows` is the number of rows in the "physical" terminal geometry (on-screen). `saveLines` is the number of saved (off-screen) lines. Look through the occurrences of both, and things like these should naturally occur to you (e.g., occurrences of CharVdev::make_cells () should literally scream at you). If I may give you some advice: code should frequently not (primarily) be read in a linear fashion like a textbook - learn to jump around searching for names, in and across files in a codebase, and look for meaning and logical connections. I use incremental-search and ag (like git-grep but faster) with helm in emacs *all the time* when working in a codebase - it's not the actual tools that are important (pick and master the ones you like) but the code reading skills they help you gain are tremendous.

**Comment by ericwq** [comment]
Thanks for your kindly help and advice. 

I performed some test with different `scrollHead`, `viewOffset` configuration. Get some idea about `viewOffset`.  

Zutty is a great project, thanks for your contribution and sharing.
